services:
  postgres:
    image: postgres
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=${DB_USER} --dbname=${DB_NAME}"]
      interval: 3s
      timeout: 2s
      retries: 10

  flyway:
    image: flyway/flyway
    container_name: flyway_container
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    command: -url=${FLYWAY_DATABASE_URL} -user=${DB_USER} -password=${DB_PASSWORD} migrate

volumes:
  postgres-data:

networks:
  bridge:
    external: true
